=== basurtoalonso/ProyectsJEE/WebMapeoXML/web/WEB-INF/xsd/navigation.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
  <xs:element name="name" />
  <xs:element name="action" type="xs:string"/>
  <xs:element name="url"  type="xs:string"> </xs:element>
  
  <xs:complexType name="NavAtt">
      <xs:simpleContent>
          <xs:extension base="xs:string"> 
              <xs:attribute name="status" default="disabled"/>
          </xs:extension>
      </xs:simpleContent>
  </xs:complexType>
  
    <xs:complexType name="nav">
      <xs:sequence>
        <xs:element name="home" type="NavAtt" />
        <xs:element name="back" type="NavAtt" />
        <xs:element name="foward" type="NavAtt" />
        <xs:element name="filter" type="NavAtt" />
        <xs:element name="new" type="NavAtt" />
        <xs:element name="refresh" type="NavAtt" />
        <xs:element name="save" type="NavAtt" />
        <xs:element name="delete" type="NavAtt" />
        <xs:element name="send" type="NavAtt" />
        <xs:element name="help" type="NavAtt" />
        <xs:element name="information" type="NavAtt" />
        <xs:element name="out" type="NavAtt" />
      </xs:sequence>
    </xs:complexType>
    
    <xs:element name="menu">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="url"/>
          <xs:element name="navbar" type="nav"/>
          <xs:element name="element" maxOccurs="unbounded">
              <xs:complexType>
                  <xs:sequence>
                      <xs:element name="name"   type="xs:string" />
                      <xs:element name="action" type="xs:string" />
                  </xs:sequence>
              </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:complexType>
    </xs:element>

</xs:schema>

=== basurtoalonso/ProyectsJEE/WebMapeoXML/web/WEB-INF/navigationXML/principal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<menu
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='../xsd/navigation.xsd'>
    <url>nav/principal</url>
    
    <navbar>
        <home status="enabled"></home>
        <back status="disabled"></back>
        <foward status="disabled"></foward>
        <filter status="disabled"></filter>
        <new status="disabled"></new>
        <refresh status="disabled"></refresh>
        <save status="disabled"></save>
        <delete status="disabled"></delete>
        <send status="disabled"></send>
        <help status="enabled"></help>
        <information status="enabled"></information>
        <out status="enabled"></out>
    </navbar>
    
    <element>
        <name>Entrada a Almacen</name>
        <action>nav/almacen</action>
    </element>
    <element>
        <name>Salida de Almacen</name>
        <action>nav/salidaAlmacen</action>
    </element>
    <element>
        <name>Confirmacion de servicios</name>
        <action>nav/servicio</action>
    </element>
    <element>
        <name>Cambio de Posicion</name>
        <action>cambio</action>
    </element>
</menu>

=== basurtoalonso/ProyectsJEE/WebMapeoXML/web/WEB-INF/navigationXML/salidaAlmacen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<menu
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='../xsd/navigation.xsd'>
    <url>nav/salidaAlmacen</url>
    <element>
        <name>Entrega contra factura</name>
        <action>entregaContraFact.jsp</action>
    </element>
    <element>
        <name>Entrega con boleta de liberacion</name>
        <action>entregaContraBoletLiberac.jsp</action>
    </element>
    <element>
        <name>Solicitud de consolidacion</name>
        <action>SolicitudConsolidacion.jsp</action>
    </element>
</menu>

=== basurtoalonso/ProyectsJEE/WebMapeoXML/web/WEB-INF/navigationXML/serie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<menu
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='../xsd/navigation.xsd'>
    <url>nav/serie</url>
    <element>
        <name>LCTPC</name>
        <action>desconsolidacion.jsp</action>
    </element>
    <element>
        <name>INTERNET</name>
        <action>desconsolidacion.jsp</action>
    </element>
</menu>

=== basurtoalonso/ProyectsJEE/WebMapeoXML/web/WEB-INF/navigationXML/almacen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<menu
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='../xsd/navigation.xsd'>
    <url>nav/almacen</url>
        
    <navbar>
        <home status="enabled"></home>
        <back status="enabled">../nav/principal</back>
        <foward status="disabled"></foward>
        <filter status="disabled"></filter>
        <new status="disabled"></new>
        <refresh status="disabled"></refresh>
        <save status="disabled"></save>
        <delete status="disabled"></delete>
        <send status="disabled"></send>
        <help status="enabled"></help>
        <information status="enabled"></information>
        <out status="enabled"></out>
    </navbar>
    
    <element>
        <name>Desconsolidaciones</name>
        <action>nav/serie</action>
    </element>
    <element>
        <name>Recepcion directa de buque</name>
        <action>nav/almacen</action>
    </element>
    <element>
        <name>Recepcion de ruta federal</name>
        <action>nav/serie</action>
    </element>
    <element>
        <name>Desconsolidacion a ruta federal</name>
        <action>nav/serie</action>
    </element>

</menu>
